### ISSUE TITLE
Tradução para língua inglesa

### ISSUE THREAD

**Issue by giovannism20** [gserrano/nerraw#9]
Não sei se é a sua intenção, mas acho que se você escrevesse o projeto em inglês, teria uma notoriedade maior tendo em vista que é um assunto MUITO badalado... :octocat:

**Comment by gserrano** [comment]
Valeu @GiovanniSM20! A aplicação em si está em inglês mesmo. Fiz a documentação em pt-br pois a intenção é facilitar para os traders brasileiros, mas vou tentar disponibilizar a mini documentação em inglês também.

**Comment by giovannism20** [comment]
@gserrano que tal mudarmos o destino desta issue para tradução ?

**Comment by gserrano** [comment]
Boa. Focar essa issue na tradução da documentação para o inglês - e nas próximos atualizações de documentação (ainda faltam alguns detalhes) deixar claro que deve ser feito nos 2 idiomas.

**Comment by giovannism20** [comment]
Com toda certeza !

**Comment by giovannism20** [comment]
@gserrano 

nerraw --> src
                  docs (com as traduções) 

O que acha dessa estrutura ?
